### ISSUE TITLE
BUG: FTA - Unable to make changes to deliverable 949 for project 1

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1191]
I have taken a local copy of production and was playing around with the deliverables in reporting mode.  When I make a change to deliverable 949 (Upscaling plans captured and disseminated through a roadmap in each country.) for project 1 and hit save, I am getting the following error:

2017-12-07_15:31:57.971 - [http-bio-18443-exec-3]DeliverableAction [ERROR]: unable to do otherPartnersAutoSave
java.lang.NullPointerException: null
	at org.cgiar.ccafs.marlo.action.projects.DeliverableAction.otherPartnersAutoSave(DeliverableAction.java:700) [classes/:na]
	at org.cgiar.ccafs.marlo.action.projects.DeliverableAction.prepare(DeliverableAction.java:808) [classes/:na]
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:167) [xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:140) [xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164) [struts2-core-2.3.32.jar:2.3.32]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:193) [xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189) [xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.project.EditDeliverableInterceptor.intercept(EditDeliverableInterceptor.java:72) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.TrimInterceptor.doIntercept(TrimInterceptor.java:58) [classes/:na]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.AccessibleStageInterceptor.intercept(AccessibleStageInterceptor.java:77) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:121) [classes/:na]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.ValidSessionCrpInterceptor.intercept(ValidSessionCrpInterceptor.java:118) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.RequireUserInterceptor.intercept(RequireUserInterceptor.java:49) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.ValidCrpActionInterceptor.intercept(ValidCrpActionInterceptor.java:56) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.InternationalitazionFileInterceptor.intercept(InternationalitazionFileInterceptor.java:130) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) [guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) [xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.DefaultActionProxy.execute(DefaultActionProxy.java:147) [xwork-core-2.3.31.jar:2.3.31]
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:575) [struts2-core-2.3.32.jar:2.3.32]
	at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81) [struts2-core-2.3.32.jar:2.3.32]
	at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99) [struts2-core-2.3.32.jar:2.3.32]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.4.jar:1.2.4]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.4.jar:1.2.4]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.4.jar:1.2.4]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.4.jar:1.2.4]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at org.cgiar.ccafs.marlo.web.filter.MARLOCustomPersistFilter.doFilter(MARLOCustomPersistFilter.java:93) [classes/:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at org.cgiar.ccafs.marlo.web.filter.RemoveSessionFromUrlFilter.doFilter(RemoveSessionFromUrlFilter.java:94) [classes/:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.79]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.79]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) [catalina.jar:7.0.79]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.79]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) [catalina.jar:7.0.79]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) [catalina.jar:7.0.79]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.79]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962) [catalina.jar:7.0.79]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.79]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445) [catalina.jar:7.0.79]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115) [tomcat-coyote.jar:7.0.79]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) [tomcat-coyote.jar:7.0.79]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318) [tomcat-coyote.jar:7.0.79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.79]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Hibernate: select fundingsou0_.id as id1_101_0_, fundingsou0_.modified_by as modified2_101_0_, fundingsou0_.created_by as created_3_101_0_, fundingsou0_.donor as donor4_101_0_, fundingsou0_.direct_donor as direct_d5_101_0_, fundingsou0_.crp_id as crp_id6_101_0_, fundingsou0_.file as file7_101_0_, fundingsou0_.type as type8_101_0_, fundingsou0_.description as descript9_101_0_, fundingsou0_.title as title10_101_0_, fundingsou0_.start_date as start_d11_101_0_, fundingsou0_.end_date as end_dat12_101_0_, fundingsou0_.extended_date as extende13_101_0_, fundingsou0_.syn_date as syn_dat14_101_0_, fundingsou0_.finance_code as finance15_101_0_, fundingsou0_.contact_person_name as contact16_101_0_, fundingsou0_.contact_person_email as contact17_101_0_, fundingsou0_.grantAmount as grantAm18_101_0_, fundingsou0_.division_id as divisio19_101_0_, fundingsou0_.status as status20_101_0_, fundingsou0_.is_active as is_acti21_101_0_, fundingsou0_.w1w2 as w22_101_0_, fundingsou0_.sync as sync23_101_0_, fundingsou0_.global as global24_101_0_, fundingsou0_.active_since as active_25_101_0_, fundingsou0_.modification_justification as modific26_101_0_ from funding_sources fundingsou0_ where fundingsou0_.id=?
Hibernate: select filedb0_.id as id1_97_0_, filedb0_.file_name as file_nam2_97_0_, filedb0_.token_id as token_id3_97_0_ from files filedb0_ where filedb0_.id=?
2017-12-07_15:31:57.978 - [http-bio-18443-exec-3]BaseAction [WARN ]: There was a problem trying to find the user center in the session.
2017-12-07_15:31:57.978 - [http-bio-18443-exec-3]BaseAction [WARN ]: There was a problem trying to find the user's center in the session.
2017-12-07_15:31:57.982 - [http-bio-18443-exec-3]UnhandledExceptionAction [ERROR]: There was an unexpected exception
java.lang.IllegalArgumentException: attempt to create saveOrUpdate event with null entity
	at org.hibernate.event.spi.SaveOrUpdateEvent.<init>(SaveOrUpdateEvent.java:62) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.event.spi.SaveOrUpdateEvent.<init>(SaveOrUpdateEvent.java:45) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionImpl.update(SessionImpl.java:731) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionImpl.update(SessionImpl.java:726) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:356) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at com.sun.proxy.$Proxy23.update(Unknown Source) ~[na:na]
	at org.cgiar.ccafs.marlo.data.dao.mysql.AbstractMarloDAO.find(AbstractMarloDAO.java:115) ~[classes/:na]
	at org.cgiar.ccafs.marlo.data.dao.mysql.FileDBMySQLDAO.find(FileDBMySQLDAO.java:54) ~[classes/:na]
	at org.cgiar.ccafs.marlo.data.manager.impl.FileDBManagerImpl.getFileDBById(FileDBManagerImpl.java:65) ~[classes/:na]
	at org.cgiar.ccafs.marlo.action.projects.DeliverableAction.prepare(DeliverableAction.java:838) ~[classes/:na]
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:167) ~[xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:140) ~[xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164) ~[struts2-core-2.3.32.jar:2.3.32]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:193) ~[xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189) ~[xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.project.EditDeliverableInterceptor.intercept(EditDeliverableInterceptor.java:72) ~[classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.TrimInterceptor.doIntercept(TrimInterceptor.java:58) ~[classes/:na]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.AccessibleStageInterceptor.intercept(AccessibleStageInterceptor.java:77) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:121) [classes/:na]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.31.jar:2.3.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.ValidSessionCrpInterceptor.intercept(ValidSessionCrpInterceptor.java:118) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.RequireUserInterceptor.intercept(RequireUserInterceptor.java:49) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.ValidCrpActionInterceptor.intercept(ValidCrpActionInterceptor.java:56) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at org.cgiar.ccafs.marlo.interceptor.InternationalitazionFileInterceptor.intercept(InternationalitazionFileInterceptor.java:130) [classes/:na]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) ~[guice-struts2-3.0.jar:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) ~[xwork-core-2.3.31.jar:2.3.31]
	at com.opensymphony.xwork2.DefaultActionProxy.execute(DefaultActionProxy.java:147) [xwork-core-2.3.31.jar:2.3.31]
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:575) [struts2-core-2.3.32.jar:2.3.32]
	at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81) [struts2-core-2.3.32.jar:2.3.32]
	at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99) [struts2-core-2.3.32.jar:2.3.32]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.4.jar:1.2.4]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.4.jar:1.2.4]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.4.jar:1.2.4]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.4.jar:1.2.4]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at org.cgiar.ccafs.marlo.web.filter.MARLOCustomPersistFilter.doFilter(MARLOCustomPersistFilter.java:93) [classes/:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at org.cgiar.ccafs.marlo.web.filter.RemoveSessionFromUrlFilter.doFilter(RemoveSessionFromUrlFilter.java:94) [classes/:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.79]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.79]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) [catalina.jar:7.0.79]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.79]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) [catalina.jar:7.0.79]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) [catalina.jar:7.0.79]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.79]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962) [catalina.jar:7.0.79]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.79]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445) [catalina.jar:7.0.79]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115) [tomcat-coyote.jar:7.0.79]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) [tomcat-coyote.jar:7.0.79]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318) [tomcat-coyote.jar:7.0.79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.79]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by cgarcia9106** [comment]
@Grant-Lay i am not sure, because the exception message localize on one line that is return null , can you please explan me a bit more

![image](https://user-images.githubusercontent.com/14946768/33717899-9f4d0e3a-db29-11e7-831e-138f09882f7c.png)

**Comment by htobon** [comment]
@Grant-Lay, can you please let us know about this? I'm quite lost on this conversation. Thank you.

**Comment by htobon** [comment]
Hi @Grant-Lay, hope you have had a good weekend. I'm going to close this issue. Please let me know if everything is ok here, otherwise please re-open it.
