### ISSUE TITLE
BUG: Null Pointer exception when saving in Project Description page

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1199]
Part of the stack trace is below.  But unfortunately I don't know anymore besides that it happens in the project description action (assuming for CRPs).  

Sebastian Amariles 2:29 PM

at org.cgiar.ccafs.marlo.web.filter.MARLOCustomPersistFilter.doFilter(MARLOCustomPersistFilter.java:95)

2:30

java.lang.NullPointerException

    at org.hibernate.action.internal.CollectionUpdateAction.execute(CollectionUpdateAction.java:105)

    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)

    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)

    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)

    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)

    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1258)

    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)

    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)

    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)

    at org.cgiar.ccafs.marlo.web.filter.MARLOCustomPersistFilter.doFilter(MARLOCustomPersistFilter.java:95)

**Comment by Grant-Lay** [comment]
Have refactored the ProjectDescriptionAction heavily so that the managed hibernate entity gets saved instead of the detached entity that is updated by the client.  Have tested in both planning and reporting mode.

**Comment by Grant-Lay** [comment]
Forgot to add the issue to the commit message but you can find it here:  
https://github.com/CCAFS/MARLO/commit/f42d82a371871aba654b0893fdff2e1d52697e93

**Comment by htobon** [comment]
@Grant-Lay and @cgarcia9106: May you please let me know if this issue is already fixed in production?

**Comment by htobon** [comment]
I have talked with Christian, and I understand that with the annualization module, this was fixed. So, I'm going to close this issue and in case thi happens again, we will create a new issue. Hope this is ok. Otherwise please let me know.
