### ISSUE TITLE
MARLO - Follow Up the Not Send Emails on Sept 4th 2018.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1565]

**Comment by HermesJim** [comment]
Update.
We Send the List of the not sends emails (with the Message ID information) to CIAT IT.

**Comment by htobon** [comment]
Hi @HermesJim, can you please update the status of this issue? Thank you.

**Comment by mralmanzar** [comment]
Buenos días Dolly,
Mi nombre es Manuel Ricardo Almanzar y estoy trabajando con Hector en CCAFS KDS.

Estuve revisando uno de los errores que ocurren al enviar los correos y encontré que cuando uno de los recipientes destinatarios del correo son inválidos el correo no se envía a ninguno de los demás correos.

javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
                com.sun.mail.smtp.SMTPAddressFailedException: 550 Invalid recipient <p.vanoort@cgiar.org> (#5.1.1)
                at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
                at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
                at javax.mail.Transport.send0(Transport.java:255)
                at javax.mail.Transport.send(Transport.java:124)
                at org.cgiar.ccafs.marlo.utils.ThreadSendMail.run(ThreadSendMail.java:60)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 Invalid recipient <p.vanoort@cgiar.org> (#5.1.1)
                at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
                ... 4 more

Vamos a tratar de controlar ese error desde acá.
Cualquier otro problema que lleguemos a tener con el envío, lo estaré documentando apropiadamente para que nos ayuden en la gestión con el proveedor.

Muchas gracias y quedo atento.

**Comment by mralmanzar** [comment]
this issue will close and was created the issue https://github.com/CCAFS/MARLO/issues/1646 in order to handle the exception.
