### ISSUE TITLE
Handle SMTPAddressFailedException sending Mails

### ISSUE THREAD

**Issue by mralmanzar** [CCAFS/MARLO#1646]
When MARLO Send a mail sometimes didn't send the mail when has an invalid recipient.

      javax.mail.SendFailedException: Invalid Addresses;
         nested exception is:
         com.sun.mail.smtp.SMTPAddressFailedException: 550 Invalid recipient <g.lay2@cgiar.org> (#5.1.1)
         at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
         at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
         at javax.mail.Transport.send0(Transport.java:255)
         at javax.mail.Transport.send(Transport.java:124)
         at org.cgiar.ccafs.marlo.utils.ThreadSendMail.run(ThreadSendMail.java:60)
         Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 Invalid recipient <g.lay2@cgiar.org> (#5.1.1)
         at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
         ... 4 more

​​​​​​​Should handle this exception on MARLO in order to avoid that the mail not be sended

**Comment by yeyo2k3** [comment]
I trying to replicate this Issue but in all cases, information about incorrect mail typed or suspended acounts is sent to MarloSupport informing about erroneous mail sent,
Validating logs on machete; I did'nt find any information about this isue since July 1/2019 to today
Code sending mails is controlled in any cases.
Cause I close this Issue for these reassons
